config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  as :user do
    get 'sign-up', to: 'devise/registrations#new', as: :sign_up
    get 'sign-in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign-out', to: 'devise/sessions#destroy', as: :sign_out
  end
  root 'locations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user

  def editable_by_user?(u)
    u.admin? || user_id == u.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :locations

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /locations
  def index
    @locations = Location.all
    if params[:query]
      @query = params[:query]
      @locations = @locations.where("name LIKE '%"+@query+"%'")
    end
  end

  # GET /locations/1
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  def create
    @location = Location.new(location_params)
    @location.user = current_user

    if @location.save
      redirect_to @location, notice: 'Location was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      redirect_to @location, notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy
    redirect_to locations_url, notice: 'Location was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    def check_user 
      unless @location.editable_by_user?(current_user)
        redirect_to locations_path, notice: "You need to be admin to edit this location"
      end
    end

    # Only allow a trusted parameter "white list" through.
    def location_params
      params.require(:location).permit(:name, :description, :latitude, :longitude, :category, :image)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "notice" then "alert-primary"
      when "success" then "alert-success"
      when "error" then "alert-danger"
      else "alert-warning"
    end
  end

  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
  def editable_by_current_user?(location)
    user_signed_in? && location.editable_by_user?(current_user)
  end

  def categories_for_select
    ["Monument", "Point of interest", "Attraction"]
  end
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  %p{class: "alert " + flash_class(key), role: "alert"}
    = value

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-light.bg-light
  = link_to "City guide", root_path, class: "navbar-brand"
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarSupportedContent
    %ul.navbar-nav.mr-auto
      %li.nav-item{class: active_class(locations_path)}
        = link_to "Locations", locations_path, class: "nav-link"
      - if user_signed_in?
        %li.nav-item{class: active_class(new_location_path)}
          = link_to "New location", new_location_path, class: "nav-link"
    = form_tag locations_path, method: "get", class: "form-inline my-2 my-lg-0" do
      = search_field_tag "query", @query ? @query : nil, {class: "form-control mr-sm-2", placeholder: "Search", "aria-label": "Search"}
      = submit_tag "Search", {class: "btn btn-outline-success my-2 my-sm-0"}
  - if user_signed_in?
    = button_to "Sign out", sign_out_path, method: "delete", class: "btn btn-danger ml-4"
  - else 
    = link_to 'Sign in', sign_in_path, class: 'btn btn-primary ml-4'

app/views/layouts/_model_errors.html.haml
- if resource.errors.any?
  .alert.alert-danger
    %h2= "#{pluralize(resource.errors.count, "error")} prohibited this location from being saved:"
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, user-scalable=no", :name => "viewport"}/
    %title Multilingual
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    .container-fluid
      = yield

app/views/locations/_form.html.haml
= form_for @location do |f|
  .card.mt-4.mb-4
    .card-header 
      %h1=title
    .card-body  
      = render 'layouts/model_errors', resource: @location

      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
      .form-group
        = f.label :description
        = f.text_area :description, class: "form-control"
      .form-group
        = f.label :latitude
        = f.text_field :latitude, class: "form-control"
      .form-group
        = f.label :longitude
        = f.text_field :longitude, class: "form-control"
      .form-group 
        = f.label :image 
        = f.text_field :image, class: "form-control"
      .form-group
        = f.label :category
        = f.select :category, categories_for_select, {}, {class: "form-control"}
    .card-footer
      .form-group
        = f.submit 'Save', class: "btn btn-primary"
        = link_to "Back", locations_path

app/views/locations/_location.html.haml
= link_to location, class: "list-group-item list-group-item-action" do 
  = location.name

app/views/locations/_location_details.html.haml
.card 
  = image_tag location.image, alt: location.name, class: 'card-img-top'
  .card-body 
    %h2.card-title=location.name
    %small.text-muted Created by #{location.user.name}
    %span.badge.badge-primary=location.category
    %p.card-text.text-justify.mt-3=location.description
    #map{style: "height: 300px; width: 100%"}
  - if editable_by_current_user?(location)
    .card-footer 
      = button_to "Edit", edit_location_path(location), class: "btn btn-warning", method: "get"
      = button_to "Delete", location, method: "delete", class: "btn btn-danger", method: "delete"


:javascript
  // Initialize and add the map
  function initMap() {
    // The location of Uluru
    var uluru = {lat: #{location.latitude}, lng: #{location.longitude}};
    // The map, centered at Uluru
    var map = new google.maps.Map(
        document.getElementById('map'), {zoom: 15, center: uluru});
    // The marker, positioned at Uluru
    var marker = new google.maps.Marker({position: uluru, map: map});
  }
/
  Load the API from the specified URL
  * The async attribute allows the browser to render the page while the API loads
  * The key parameter will contain your own API key (which is not needed for this tutorial)
  * The callback parameter executes the initMap() function
%script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyC44VyGXZ-9yZ0qrAtqij82pykgvtjKaK4&callback=initMap"}
  :cdata 

app/views/locations/edit.html.haml
.row 
  .col-12.col-md-6.offset-md-3
    = render 'form', title: 'Edit location'

app/views/locations/index.html.haml
%h1.text-center.mt-4.mb-4 Best city locations
.row 
  .col-12.col-md-6.offset-md-3
    - if @locations.count > 0
      .list-group
        = render @locations 
    - else 
      .alert.alert-warning #{@query? "No locations match your search" : "No locations registered yet"}

app/views/locations/new.html.haml
.row 
  .col-12.col-md-6.offset-md-3
    = render 'form', title: 'New location'

app/views/locations/show.html.haml
.row 
  .col-12.col-md-6.offset-md-3.mt-4.mb-4
    = render 'location_details', location: @location